### PR TITLE
Transfer parameters fetched by index, not by name

### LINKED ISSUE #784: Invalid fallback `0x0` for transfer decoding
**Describe the bug**
We fallback to `0x0` while attempting transfer decoding for transactions. This breaks clients as it is not a valid address.

**To Reproduce**
In the response: https://safe-client.staging.gnosisdev.com/v1/chains/4/safes/0x1C8b9B78e3085866521FE206fa4c1a67F49f153A/transactions/history

check
```
txId = multisig_0x1C8b9B78e3085866521FE206fa4c1a67F49f153A_0x0437839bd4e5449c474b93328b1e27eb2f387e71eb0992f09da7ba4d484905a7
```

**Expected behavior**
Whenever falling back to a `0x0` address make sure to fallback to the correct length `0x0000000000000000000000000000000000000000`

- Adjust default values here:
https://github.com/gnosis/safe-client-gateway/blob/main/src/routes/transactions/converters/mod.rs#L131
https://github.com/gnosis/safe-client-gateway/blob/main/src/routes/transactions/converters/mod.rs#L104

- Replace usage of https://github.com/gnosis/safe-client-gateway/blob/main/src/utils/mod.rs#L45 with https://github.com/gnosis/safe-client-gateway/blob/e43b2175d653cca6ae835c2459668f544ac3b4c3/src/utils/mod.rs#L89

**Environment (please complete the following information):**
 - Staging 

**Additional context**
- The problem lies on having a parameter names unexpected by the CGW in the transfer:

```json
"dataDecoded": {
        "method": "transfer",
        "parameters": [
          {
            "name": "dst",
            "type": "address",
            "value": "0x1C8b9B78e3085866521FE206fa4c1a67F49f153A"
          },
          {
            "name": "wad",
            "type": "uint256",
            "value": "10000000000000000"
          }
        ]
      }
```

The original transaction can be found [here](https://safe-transaction.staging.gnosisdev.com/api/v1/safes/0x1C8b9B78e3085866521FE206fa4c1a67F49f153A/multisig-transactions/?safe_tx_hash=0x0437839bd4e5449c474b93328b1e27eb2f387e71eb0992f09da7ba4d484905a7)

### PR DESCRIPTION
**Pull request by jpalvarezl**
Closes #784 

References:
- https://eips.ethereum.org/EIPS/eip-20
- https://eips.ethereum.org/EIPS/eip-721

Notes: 
- There are 2 tests that for some reason try to ignore the method name that were added at some point. I propose to remove them as they seem to be flat out wrong:
https://github.com/gnosis/safe-client-gateway/blob/e43b2175d653cca6ae835c2459668f544ac3b4c3/src/routes/transactions/converters/tests/check_sender_or_receiver.rs#L40
https://github.com/gnosis/safe-client-gateway/blob/e43b2175d653cca6ae835c2459668f544ac3b4c3/src/routes/transactions/converters/tests/check_sender_or_receiver.rs#L57

- I've included a test covering the issue `transfer` case (unexpected paramter names)

### CODE REVIEW

**Review by Uxio0 — APPROVED** [review]
Looks good @jpalvarezl

File: src/routes/transactions/converters/mod.rs [hunk 1]
```diff
@@ -101,7 +101,10 @@ impl SafeTransaction {
         info_provider: &impl InfoProvider,
     ) -> Transfer {
         let sender = get_from_param(&self.data_decoded, &self.safe);
-        let recipient = get_to_param(&self.data_decoded, "0x0");
+        let recipient = get_to_param(
+            &self.data_decoded,
+            "0x0000000000000000000000000000000000000000",
```
Comment (rmeissner) [inline src/routes/transactions/converters/mod.rs:106]: We could have made this a constant ;)
